import { setupI18n } from "@lingui/core";

// this file is generated by the cli
import enMessages from "./locales/en/messages.js";
import frMessages from "./locales/fr/messages.js";

// import this constant as get translations from it outside of React
export default setupI18n({
  language: "fr",
  catalogs: {
    en: enMessages,
    fr: frMessages,
  },
});
