version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - '${PRISMA_PORT}:${PRISMA_PORT}'
    environment:
      PRISMA_CONFIG: |
        port: ${PRISMA_PORT}
        databases:
          default:
            connector: mongo
            database: db_muddle
            uri: ${PRISMA_DB_URI}